version: 2

multi-ecosystem-groups:
  frontend:
    schedule:
      interval: "weekly"
  docs:
    schedule:
      interval: "weekly"
  backend:
    schedule:
      interval: "weekly"
  compose:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "docker"
    directory: "/frontend"
    patterns: ["*"]
    multi-ecosystem-group: "frontend"
  - package-ecosystem: "npm"
    directory: "/frontend"
    patterns: ["*"]
    multi-ecosystem-group: "frontend"
    
  - package-ecosystem: "docker"
    directory: "/docs"
    patterns: ["*"]
    multi-ecosystem-group: "docs"
  - package-ecosystem: "npm"
    directory: "/docs"
    patterns: ["*"]
    multi-ecosystem-group: "docs"
    
  - package-ecosystem: "docker"
    directory: "/backend"
    patterns: ["*"]
    multi-ecosystem-group: "backend"
  - package-ecosystem: "dotnet-sdk"
    directory: "/backend"
    patterns: ["*"]
    multi-ecosystem-group: "backend"
    
  - package-ecosystem: "docker-compose"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "compose"
