networks:
  my_network:
    name: my_network
    driver: bridge

secrets:
  oauth_client_secret:
    file: ./oauth_client_secret.secret
  postgres_password:
    file: ./postgres_password.secret

services:
  # Start database
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Start backend after database
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME:-Koala}
      - OAUTH_PROVIDER_URL=${OAUTH_PROVIDER_URL:-https://koala.dev.svsticky.nl}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=database;Port=5432;Username=postgres;Password=<PASSWORD>;Database=postgres;Include Error Detail=true
    secrets:
      - oauth_client_secret
      - postgres_password
    volumes:
      - ./backend:/app
      - /app/bin
      - /app/obj
    depends_on:
      database:
        condition: service_healthy
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 150s

  # Start frontend after backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
      no_cache: true
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME:-Koala}
      - NEXT_PUBLIC_OAUTH_PROVIDER_URL=${OAUTH_PROVIDER_URL}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    secrets:
      - oauth_client_secret
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - my_network

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
      target: development
      no_cache: true
    ports:
      - "${DOCS_PORT:-3000}:3001"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./docs:/app/docs
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /app/node_modules
      - /app/.next
    networks:
      - my_network
