networks:
  prod_network:
    name: prod_network
    driver: bridge

secrets:
  oauth_client_secret:
    file: ./oauth_client_secret.secret
  postgres_password:
    file: ./postgres_password.secret

services:
  # Production database with persistent volume
  database:
    user: root
    privileged: true
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent volume
    networks:
      - prod_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  # Production backend
  backend:
    user: root
    privileged: true
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production # Use production target
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Host=database;Port=5432;Username=postgres;Password=<PASSWORD>;Database=postgres;
      - OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME:-Koala}
      - OAUTH_PROVIDER_URL=${OAUTH_PROVIDER_URL:-https://koala.svsticky.nl/}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - ADMIN_CLAIM=${ADMIN_CLAIM:-is_admin}
    secrets:
      - oauth_client_secret
      - postgres_password
    extra_hosts:
      - "koala.dev.svsticky.nl:host-gateway"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - prod_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  # Production frontend
  frontend:
    user: root
    privileged: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production # Use production target
      args:
        NEXT_PUBLIC_OAUTH_PROVIDER_NAME: ${OAUTH_PROVIDER_NAME:-Koala}
        NEXT_PUBLIC_OAUTH_PROVIDER_URL: ${OAUTH_PROVIDER_URL:-https://koala.svsticky.nl/}
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME:-Koala}
      - NEXT_PUBLIC_OAUTH_PROVIDER_URL=${OAUTH_PROVIDER_URL:-https://koala.svsticky.nl/}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - THEME_COLOR=${THEME_COLOR:-#FA6B20}
      - NEXTAUTH_URL=${HOST_URL:-http://localhost:3000}
    secrets:
      - oauth_client_secret
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - prod_network
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
      target: production # Use production target
    ports:
      - "${DOCS_PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
    networks:
      - prod_network
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  postgres_data: # Persistent volume for database
